# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelDiary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!	
  pod 'TKSubmitTransition', :git => 'https://github.com/entotsu/TKSubmitTransition.git', :branch => 'swift4'
  pod 'DatePicker', '1.0.0'
  pod 'IQKeyboardManagerSwift', '6.0.4'
  pod 'SideMenu'
  pod 'SwiftyGif'
  pod 'SwiftyOnboard'
  pod 'Alamofire'
  pod 'expanding-collection'
  pod 'FoldingCell'
  pod 'paper-onboarding'
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for TravelDiary
  pod 'Firebase/Messaging'


end
